package com.syntaxphoenix.syntaxapi.test.json.utils;

public final class JsonData {

    private JsonData() {}

    public static final String PRETTY_DATA = String.join("\n", new String[] {
        "{",
        "  \"title\": \"Willkommen auf Among Retards!\",",
        "  \"color\": \"#bd0d54\",",
        "  \"footer\": {",
        "    \"text\": \"Copyright @ Among Retards\"",
        "  },",
        "  \"description\": [",
        "    \"Among Retards ist ein kleiner Community Server, der als kleine Among Us Gaming Gruppe anfing.\",",
        "    \"Nun da weitere Projekte auf dem Server betrieben werden, sahen wir das als Anfang einer neuen Era des Servers.\",",
        "    \"Wir begangen zu Planen und streben nun an ein Community Server für Gaming und Unterhaltung zu sein.\",",
        "    \"\",",
        "    \"Ein Projekt ist hierbei eine Gruppe von Personen die ein Spiel in einer bestimmten Weise auf unserem Discord auslebt.\",",
        "    \"Projekte können von jedem eingereicht und geleitet werden, dazu können vorhandene Projekte auch von jedem verändert werden.\",",
        "    \"Dafür haben wir folgende Formulare dafür vorbereitet:\",",
        "    \"\",",
        "    \"__Projekt einreichen__: https://forms.gle/wQzyFRgfLWiqXXiR8\",",
        "    \"__Projekt verändern__: https://forms.gle/enDJ8W7gP6TZY6RL6\",",
        "    \"\",",
        "    \"\",",
        "    \"\",",
        "    \"**Regeln:**\"",
        "  ],",
        "  \"fields\": [",
        "    {",
        "      \"name\": \"1. Interaktion\",",
        "      \"description\": [",
        "            \"1.1. Der Umgang untereinander hat freundlich und respektvoll abzulaufen.\",",
        "            \"1.2. Die Belästigung anderer Personen zu organisieren, daran teilzunehmen oder dazu aufzurufen ist verboten.\",",
        "            \"1.3. Das wiederholende senden von gleichen oder sehr ähnlichen Nachrichten (Spam) ist nicht gestattet.\",",
        "            \"1.4. Das Versenden von Freundschaftsanfragen oder Nachrichten an eine Person, ganz besonders nachdem die empfangende Person klar gemacht hat, dass kein weiterer Kontakt erwünscht ist, wird nicht geduldet\",",
        "            \"1.5. Das Androhen von Gewalt oder Schaden gegen andere ist verboten. Dazu gehören indirekte Drohungen, sowie das Teilen personenbezogener Daten oder das Androhen davon.\",",
        "            \"1.6. Rassismus jegweder Art ist strengstens untersagt.\",",
        "            \"1.7. Das umgehen von Ausschlüssen von Projekten oder des Servers wird nicht geduldet.\",",
        "            \"1.8. Das Verwenden von Soundboards, Stimmversteller o.ä. ist gestattet, allerdings müssen alle im Channel anwesenden Personen damit einverstanden sein.\"",
        "      ]",
        "    },",
        "    {",
        "      \"name\": \"2. Inhalte (Sprache, Text und Medien)\",",
        "      \"description\": [",
        "        \"2.1. Pornographie jeglicher Art ist verboten.\",",
        "        \"2.2. Jegliche Sexualisierung von Minderjährigen ist verboten.\",",
        "        \"2.3. Die Verbreitung oder Förderung von gewalttätigem Extremismus sowie Exremistische Inhalte und Kommentare sind strengstens untersagt.\",",
        "        \"2.4. Inhalte, die rohe Gewalt oder Tierquälerei enthalten, sind verboten.\",",
        "        \"2.5. Kommentare, Medien oder Aussagen die Suizid oder Selbstverletzung verherrlichen oder andere dazu ermutigen sind untersagt.\",",
        "        \"2.6. Das Versenden von Schadsoftware, Viren oder Verlinkungen zu diesen sind verboten.\"",
        "      ]",
        "    },",
        "    {",
        "      \"name\": \"3. Projekte\",",
        "      \"description\": [",
        "        \"3.1. Die Regeln eines Projekts sind einzuhalten.\",",
        "        \"3.2. Den Anweisungen der Moderatoren eines Projektes sind folgezuleisten, solange diese nicht gegen die Regeln verstoßen.\"",
        "      ]",
        "    },",
        "    {},",
        "    {",
        "      \"name\": \"Team\",",
        "      \"description\": [",
        "        \"Unser Team enthält sich das Recht vor, die Regeln jederzeit zu ändern und Ausschlüsse so wie allgemeine Strafen\",",
        "        \"nach einer Teambesprechung auszusetzen oder zu vergeben.\",",
        "        \"\",",
        "        \"**@Lauriichan (Laura)**\",",
        "        \"Kleine passiv aktive Streamerin auf Twitch, die generell sehr vieles spielt und auch streamt, mag besonders Echtzeitstrategiespiele.\",",
        "       \"Entwicklerin von Among Retards die sich um den Bot sowie die Verwaltung eigener Server kümmert.\",",
        "        \"\",",
        "        \"**@Jaschal (Alexander / Alex)**\",",
        "        \"Ist als typischer Zocker für jeden Spaß zu haben und ist legt seinen Fokus auf Strategiespiele, dazu LoL und liebt Paradox Games.\",",
        "        \"Mehr oder weniger Streitschlichter von Among Retards der sich auch gern Unterhält.\",",
        "        \"\",",
        "        \"**@Hochlord Leonidas (Leonidas / Leo)**\",",
        "        \"Als ehemaliger Lets Player ein großer Fan von Strategiespielen, allen voran die Paradox und Blizzard Spiele, aber auch Rollenspiele wie Diablo und WoW.\",",
        "        \"Begründer von Among Retards, um eine Gaming Community zu formen die Spaß hat zusammen zu spielen.\"",
        "      ]",
        "    }",
        "  ]",
        "}"
    });

}
